name: recog
version: 1.2.3
date: 24/09/2014
description: A collection of group recognition methods

authors:
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Ákos Seress
    - name: Nurullah Ankaralioglu
      url: mailto:ankarali@atauni.edu.tr
    - name: Peter Brooksbank
      url: http://www.facstaff.bucknell.edu/pbrooksb/
    - name: Frank Celler
      url: http://www.celler.de/
    - name: Stephen Howe
    - name: Maska Law
      url: mailto:maska@maths.uwa.edu.au
    - name: Steve Linton
      url: http://www-circa.mcs.st-and.ac.uk/~sal/
    - name: Gunter Malle
      url: http://www.mathematik.uni-kl.de/~malle/
    - name: Alice Niemeyer
      url: http://www.maths.uwa.edu.au/~alice/
    - name: Eamonn O'Brien
      url: http://www.math.auckland.ac.nz/~obrien/
    - name: Colva M. Roney-Dougal
      url: http://www-groups.mcs.st-and.ac.uk/~colva

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">=4.4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Forms"
      version: ">= 1.2"
      url: "http://cage.ugent.be/geometry/forms.php"
    - name: "genss"
      version: ">= 1.3"
      url: "http://gap-system.github.io/genss/"
    - name: "Orb"
      version: ">= 3.4"
      url: "http://gap-system.github.io/orb/"
    - name: "FactInt"
      version: ">= 1.5.2"
      url: "http://www.gap-system.org/DevelopersPages/StefanKohl/factint.html"
    - name: "AtlasRep"
      version: ">= 1.4.0"
      url: "http://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep"
    - name: "recogbase"
      version: ">= 1.0"
      url: "http://gap-system.github.io/recogbase/"

www: http://gap-system.github.io/recog/
readme: http://gap-system.github.io/recog/README
packageinfo: http://gap-system.github.io/recog/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/recog/releases/download/v1.2.3/recog-1.2.3.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-system/recog/releases/download/v1.2.3/recog-1.2.3.tar.bz2

abstract: <b>Warning:</b> This package is still under development and    this version is to be considered a working, but preliminary one. <p/>    This packages contains a collection of methods for the    constructive recognition of groups. It is mostly intended for    permutation groups, matrix groups and projective groups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
