name: recog
version: 1.2.1
date: 31/04/2014
description: A collection of group recognition methods

authors:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Akos Seress
      url: http://www.math.ohio-state.edu/~akos/
    - name: Nurullah Ankaralioglu
      url: mailto:ankarali@atauni.edu.tr
    - name: Peter Brooksbank
      url: http://www.facstaff.bucknell.edu/pbrooksb/
    - name: Frank Celler
      url: http://www.celler.de/
    - name: Stephen Howe
    - name: Maska Law
      url: mailto:maska@maths.uwa.edu.au
    - name: Steve Linton
      url: http://www-circa.mcs.st-and.ac.uk/~sal/
    - name: Gunter Malle
      url: http://www.mathematik.uni-kl.de/~malle/
    - name: Alice Niemeyer
      url: http://www.maths.uwa.edu.au/~alice/
    - name: Eamonn O'Brien
      url: http://www.math.auckland.ac.nz/~obrien/
    - name: Colva M. Roney-Dougal
      url: http://www-groups.mcs.st-and.ac.uk/~colva

GAP: ">=4.4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
    - name: "Forms"
      version: ">= 1.2"
    - name: "genss"
      version: ">= 1.3"
    - name: "Orb"
      version: ">= 3.4"
    - name: "FactInt"
      version: ">= 1.5.2"
    - name: "AtlasRep"
      version: ">= 1.4.0"
    - name: "recogbase"
      version: ">= 1.0"

www: http://neunhoef.github.io/recog/
readme: http://neunhoef.github.io/recog/README
packageinfo: http://neunhoef.github.io/recog/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/neunhoef/recog/releases/download/v1.2.1/recog-1.2.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/neunhoef/recog/releases/download/v1.2.1/recog-1.2.1.tar.bz2

abstract: <b>Warning:</b> This package is still under development and    this version is to be considered a working, but preliminary one. <p/>    This packages contains a collection of methods for the    constructive recognition of groups. It is mostly intended for    permutation groups, matrix groups and projective groups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
